// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://5w5heh54zzh3hmunuskdarasia.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "eu-west-2:b01ebd25-1a95-458d-a8b1-3a712d013a95",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_KfnKWh1q4",
    "aws_user_pools_web_client_id": "3vbsoqjc61ok4ftr69fd299qdv",
    "oauth": {}
};


export default awsmobile;
