// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'eu-west-2',
    aws_appsync_graphqlEndpoint: 'https://sbwsnv45u5emjln2ykvzmpbx6y.appsync-api.eu-west-2.amazonaws.com/graphql',
    aws_appsync_region: 'eu-west-2',
    aws_appsync_authenticationType: 'API_KEY',
    aws_appsync_apiKey: 'da2-m4v3n5kqpnad3i3bz3aiywca24'
};


export default awsmobile;
